- name: demo on play level variable
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: url - {{ URL }}

- name: for task level demo
  hosts: all
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: URL - {{ URL }}
        vars:
          URL: EXAMPLE.COM