- name: demo on play level variable
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: url - {{ URL }}

- name: Demo on Task Level Variables
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
        URL: tasks.example.com