- name: Demo on Play Level Variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

# task level

- name: Demo on Task Level Variables
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
        URL: tasks.example.com

- name: Variable from Roles
  hosts: all
  vars:
    URL_PLAY: play.example.com
  roles:
    - sample

- name: demo on register variables
  hosts: all
  tasks:
    - name: run uptime shell command
      ansible.builtin.shell: uptime