- name: print parameter
  hosts: localhost
  connection: local
  tasks:
    - name: print parameter
      ansible.builtin.debug:
        msg: parameter - {{ lookup('test.test', region='us-east-1' ) }}